nodeLinker: node-modules
enableScripts: false
packageExtensions:
  "@rspack/core@*":
    dependencies:
      "@module-federation/runtime-tools": "^2.0.0"
  "@module-federation/sdk@*":
    dependencies:
      process: "^0.11.10"
